"""
Centralised configuration for the Route Recommender backend.

Every environment variable used anywhere in the app must be declared here.
Fields with no default are REQUIRED — the service raises ValidationError
at import time if they are absent, preventing silent misconfiguration.
"""

from pathlib import Path
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict

# WHY __file__: resolve .env relative to this file's location (backend/app/),
# not relative to CWD. This means uvicorn can be started from any directory
# (backend/, repo root, etc.) and still find the repo-root .env.
_REPO_ROOT = Path(__file__).resolve().parents[2]  # backend/app/config.py → repo root
_ENV_FILE = _REPO_ROOT / ".env"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=str(_ENV_FILE),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # --- Cosmos DB (read-only) ---
    # WHY: no default — service refuses to start if this env var is absent
    COSMOS_CONNECTION_STRING: str
    COSMOS_DATABASE_NAME: str = "route_recommender"
    COSMOS_CONTAINER_NAME: str = "structured_crimes"

    # --- GraphHopper routing (Phase 8) ---
    # Local dev: http://localhost:8989 (docker compose up graphhopper)
    # Production: Cloudflare Tunnel URL (set in Azure Container Apps env vars)
    GRAPHHOPPER_URL: str = "http://localhost:8989"

    # Default routing profile when the request doesn't specify one.
    # "fastest" = travel time only. "balanced" = moderate crime penalty (λ=0.1).
    # "safest" = strong crime penalty (λ=0.3).
    SAFETY_PROFILE: str = "balanced"

    # Comma-separated list of valid profile names. Used to validate per-request
    # profile selection so unknown values are rejected before reaching GH.
    GRAPHHOPPER_PROFILES: str = "fastest,balanced,safest"

    # --- MLflow ---
    MLFLOW_TRACKING_URI: str = "sqlite:///ml/artifacts/mlruns.db"
    MLFLOW_REGISTRY_URI: str = "sqlite:///ml/artifacts/mlruns.db"

    # --- CORS ---
    # WHY: stored as a comma-separated string in env; split to list at usage
    # site rather than here, to keep the Settings model serialisable to JSON
    ALLOWED_ORIGINS: str = "http://localhost:3000,https://route-recommender-web.vercel.app"

    # --- Logging ---
    LOG_LEVEL: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"
    # WHY: Literal type means Pydantic validates the value against the enum
    # at startup — typo "jsn" fails fast instead of producing silent no-op
    LOG_FORMAT: Literal["json", "console"] = "console"

    # --- Risk model ---
    # Directory containing per-category KDE pkl files produced by ml/train_kde.py.
    # No default — service refuses to start without trained model artifacts.
    KDE_ARTIFACTS_DIR: str

    # Banding thresholds — p33/p66 of real ROUTE total_scores (not per-point
    # densities). score_route() returns route_eta_sec × mean(per-waypoint score),
    # so thresholds live on that accumulated scale (~10^4), NOT raw KDE density.
    # Regenerate after each retrain with: python -m ml.calibrate_bands
    # (routes 150 Delhi pairs through GH at noon, USE_LIGHTGBM matching the backend).
    BAND_LOW_THRESHOLD: float = 35671.76   # Low / Medium boundary  (p33)
    BAND_HIGH_THRESHOLD: float = 58229.06  # Medium / High boundary (p66)

    # How often (seconds) the background task checks the MLflow registry
    # for a newer Production model. Default: 3600 (hourly).
    MODEL_RELOAD_INTERVAL_SECONDS: int = 3600

    # Path to the pre-computed heatmap GeoJSON (generated by ml/generate_heatmap.py).
    # Relative paths are anchored to repo root at request time.
    HEATMAP_PATH: str = "ml/artifacts/heatmap.geojson"
    HEATMAP_IMAGE_PATH: str = "ml/artifacts/heatmap.png"

    # --- LightGBM ensemble (Phase 4) ---
    # WHY False default: safe rollback — if LightGBM artifacts are missing or
    # produce worse banding, flip to False and the backend reverts to pure KDE.
    USE_LIGHTGBM: bool = False

    # Directory containing lgb_*.pkl files produced by ml/train_lightgbm.py.
    # Defaults to the same dir as KDE artifacts.
    LGB_ARTIFACTS_DIR: str = "ml/artifacts"

    # Ensemble blend weights. Must sum to 1.0 (enforced in risk_model.py).
    KDE_ENSEMBLE_WEIGHT: float = 0.7
    LGB_ENSEMBLE_WEIGHT: float = 0.3

    # --- Geocoding ---
    # Primary geocoder: Mappls (MapMyIndia). Empty = skip Mappls, fall straight to Nominatim.
    MAPPLS_API_KEY: str = ""

    # --- Retrieval (Qdrant + hybrid search) ---
    # WHY empty default: if QDRANT_HOST is not set, the retrieval service is
    # a no-op — /routes/recommend still works, just without nearby_incidents.
    # Set to "localhost" in .env when running Qdrant via docker-compose locally.
    QDRANT_HOST: str = ""
    QDRANT_PORT: int = 6333
    # Qdrant Cloud — takes precedence over QDRANT_HOST/QDRANT_PORT when set.
    # URL format: https://<cluster-id>.<region>.gcp.cloud.qdrant.io
    QDRANT_URL: str = ""
    QDRANT_API_KEY: str = ""
    # Path to the BM25 model pickle produced by retrieval/pipeline.py.
    # Relative paths are anchored to repo root at startup.
    BM25_MODEL_PATH: str = "retrieval/bm25_model.pkl"

    # --- Voice AI Agent ---
    # LLM_PROVIDER controls which LLM the CrewAI agent uses.
    # "ollama"    → local Ollama (free, private, no internet needed)
    # "groq"      → Groq Cloud API (free tier, fast, works in production)
    # "anthropic" → Claude via Anthropic API (cloud, needs API key)
    LLM_PROVIDER: Literal["ollama", "groq", "anthropic"] = "ollama"

    # Ollama settings (used when LLM_PROVIDER="ollama")
    # host.docker.internal reaches the Windows host from inside a Docker container.
    # Change to http://localhost:11434 when running backend directly on host.
    OLLAMA_BASE_URL: str = "http://host.docker.internal:11434"
    OLLAMA_MODEL: str = "gemma4:e4b"

    # Groq settings (used when LLM_PROVIDER="groq")
    # Free tier: https://console.groq.com — instant API key, no approval needed.
    GROQ_API_KEY: str = ""
    GROQ_MODEL: str = "llama-3.3-70b-versatile"

    # Anthropic settings (used when LLM_PROVIDER="anthropic")
    ANTHROPIC_API_KEY: str = ""
    AGENT_MODEL: str = "claude-sonnet-4-6"

    # Whisper transcription model size. Larger = more accurate, slower.
    # "base" is a good balance for clear speech in a quiet room.
    WHISPER_MODEL_SIZE: Literal["tiny", "base", "small"] = "base"
    # "cpu" always in Docker (no GPU in Azure Container Apps Consumption plan).
    # Set to "cuda" only on a host that has an NVIDIA GPU + CUDA toolkit installed.
    WHISPER_DEVICE: Literal["cpu", "cuda"] = "cpu"

